### ISSUE TITLE
Issues with map panning interaction

### ISSUE THREAD

**Issue by jldevelop** [Ambiarc/Feedback-Tracker#10]
Sometimes some areas of map are not interactable space, and cause issue with map intearction. 
It depends on map position and rotaition. Some areas of the maps are interactable only until you reach one point ("invisible vertical line") on the screen, and after that, area becomes unresponsive, so you need to click on other place on the map in order to move it.

Here's a video description: 
https://slack-files.com/T0QGXU14P-FA9D9CB7B-8ad15aacd6

**Comment by aarnrvera** [comment]
We tracked this down. If the issue persists let me know for a map update.
