### ISSUE TITLE
Triggering exterior

### ISSUE THREAD

**Issue by jldevelop** [Ambiarc/Feedback-Tracker#2]
Triggering exterior view is a bit tricky. In order to trigger exterior, we need to call focusOnFloor method, but floorId parameter needs to be null. Could be a good idea to put that in documentation. 
Maybe "Exterior" could be used as a id for triggering exterior instead of null?

**Comment by aarnrvera** [comment]
would addressing Guidekick/Ambiarc#3 fix this issue?
