### ISSUE TITLE
Exterior as an option in BuildingID

### ISSUE THREAD

**Issue by jldevelop** [Ambiarc/Feedback-Tracker#3]
Looking at current structure, exterior looks more like floor type and not buidling type. In order to trigger exterior, building id argument needs to be provided in SDK call, with floorId argument null.
More intuitive way of triggering exterior could be to send "Exterior" as buildingId, or simply call focusOnFloor method withoud any parameters?
Maybe we could add Exterior in buidings list as a default building, so we can fetch it with getAllBuildings along with other "regular" buildings?

**Comment by aarnrvera** [comment]
This is addressed in 1.1
