### ISSUE TITLE
Unable to place/reposition icon over 70% percent of screen width

### ISSUE THREAD

**Issue by jldevelop** [Ambiarc/Feedback-Tracker#9]
When I create maplabel and want to reposition it to another place with right click, I can do it only on part of the x plane of the screen.
For example, if I right on any place that has x value less than cca 70% of screen width, everything works fine, but if I right click over these 70%, maplabel is being positioned in the center of the screen. These 70% is sometimes 60%, and sometimes up to 90% of screen width - it changes as I move the map (but not sure if it moves proportionaly....).
Other maps seem to work fine

https://files.slack.com/files-pri/T0QGXU14P-FA9DK9DAB/download/positioning_issue.mp4

**Comment by aarnrvera** [comment]
We tracked this issue down to a unity issue, it should be fixed in newer updates
